$(document).ready(function(){
$(".santa").click(function(){
        padre=santa;
        $("#h3l3").html(padre[0]["Ability"]["nombre"]);
        $("#h3l2").html(padre[1]["Ability"]["nombre"]);
        $("#h3l1").html(padre[2]["Ability"]["nombre"]);
        $("#h2l3").html(padre[3]["Ability"]["nombre"]);
        $("#h2l2").html(padre[4]["Ability"]["nombre"]);
        $("#h2l1").html(padre[5]["Ability"]["nombre"]);
        $("#h1l3").html(padre[6]["Ability"]["nombre"]);
        $("#h1l2").html(padre[7]["Ability"]["nombre"]);
        $("#h1l1").html(padre[8]["Ability"]["nombre"]);
    });
    $(".rudolf").click(function(){
        padre=rudolf;
        $("#h3l3").html(padre[0]["Ability"]["nombre"]);
        $("#h3l2").html(padre[1]["Ability"]["nombre"]);
        $("#h3l1").html(padre[2]["Ability"]["nombre"]);
        $("#h2l3").html(padre[3]["Ability"]["nombre"]);
        $("#h2l2").html(padre[4]["Ability"]["nombre"]);
        $("#h2l1").html(padre[5]["Ability"]["nombre"]);
        $("#h1l3").html(padre[6]["Ability"]["nombre"]);
        $("#h1l2").html(padre[7]["Ability"]["nombre"]);
        $("#h1l1").html(padre[8]["Ability"]["nombre"]);
    });
    $(".gnome").click(function(){
        padre=gnome;
        $("#h3l3").html(padre[0]["Ability"]["nombre"]);
        $("#h3l2").html(padre[1]["Ability"]["nombre"]);
        $("#h3l1").html(padre[2]["Ability"]["nombre"]);
        $("#h2l3").html(padre[3]["Ability"]["nombre"]);
        $("#h2l2").html(padre[4]["Ability"]["nombre"]);
        $("#h2l1").html(padre[5]["Ability"]["nombre"]);
        $("#h1l3").html(padre[6]["Ability"]["nombre"]);
        $("#h1l2").html(padre[7]["Ability"]["nombre"]);
        $("#h1l1").html(padre[8]["Ability"]["nombre"]);
    });
    $(".h3l3").click(function(){
        $(".nom").html(padre[0]["Ability"]["nombre"]);
        $(".desc1").html(padre[2]["Ability"]["descript"]);
        $(".diva").css('opacity', '0.3');
        $(".desc2").html(padre[1]["Ability"]["descript"]);
        $(".divb").css('opacity', '0.3');
        $(".desc3").html(padre[0]["Ability"]["descript"]);
    });
    $(".h3l2").click(function(){
        $(".nom").html(padre[1]["Ability"]["nombre"]);
        $(".desc1").html(padre[2]["Ability"]["descript"]);
        $(".desc2").html(padre[1]["Ability"]["descript"]);
        $(".desc3").html(padre[0]["Ability"]["descript"]);

    });
    $(".h3l1").click(function(){
        $(".nom").html(padre[2]["Ability"]["nombre"]);
        $(".desc1").html(padre[2]["Ability"]["descript"]);
        $(".desc2").html(padre[1]["Ability"]["descript"]);
        $(".desc3").html(padre[0]["Ability"]["descript"]);
    });
    $(".h2l3").click(function(){
        $(".nom").html(padre[3]["Ability"]["nombre"]);
        $(".desc1").html(padre[5]["Ability"]["descript"]);
        $(".desc2").html(padre[4]["Ability"]["descript"]);
        $(".desc3").html(padre[3]["Ability"]["descript"]);
    });
    $(".h2l2").click(function(){
        $(".nom").html(padre[4]["Ability"]["nombre"]);
        $(".desc1").html(padre[5]["Ability"]["descript"]);
        $(".desc2").html(padre[4]["Ability"]["descript"]);
        $(".desc3").html(padre[3]["Ability"]["descript"]);
    });
    $(".h2l1").click(function(){
        $(".nom").html(padre[5]["Ability"]["nombre"]);
        $(".desc1").html(padre[5]["Ability"]["descript"]);
        $(".desc2").html(padre[4]["Ability"]["descript"]);
        $(".desc3").html(padre[3]["Ability"]["descript"]);
    });
    $(".h1l3").click(function(){
        $(".nom").html(padre[6]["Ability"]["nombre"]);
        $(".desc1").html(padre[8]["Ability"]["descript"]);
        $(".desc2").html(padre[7]["Ability"]["descript"]);
        $(".desc3").html(padre[6]["Ability"]["descript"]);
    });
    $(".h1l2").click(function(){
        $(".nom").html(padre[7]["Ability"]["nombre"]);
        $(".desc1").html(padre[8]["Ability"]["descript"]);
        $(".desc2").html(padre[7]["Ability"]["descript"]);
        $(".desc3").html(padre[6]["Ability"]["descript"]);
    });
    $(".h1l1").click(function(){
        $(".nom").html(padre[8]["Ability"]["nombre"]);
        $(".desc1").html(padre[8]["Ability"]["descript"]);
        $(".desc2").html(padre[7]["Ability"]["descript"]);
        $(".desc3").html(padre[6]["Ability"]["descript"]);
    });
});